[phases.setup]
nixPkgs = ["python311", "nodejs_18"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "npm install"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "./start.sh"